CREATE SCHEMA MOBILEANALYSIS;

USE MOBILEANALYSIS;

SELECT * FROM MOBILE;

-- TO CHECK MOBILE FEATURES AND PRICE LIST 
SELECT PHONE_NAME,PRICE FROM MOBILE;

-- TO FIND THE PRICE OF MOST EXPENSIVE PHONE
SELECT * FROM MOBILE 
ORDER BY PRICE  DESC 
LIMIT 5;

-- TO FIND THE PRICE OF MOST CHEAPEST PHONE
SELECT * FROM MOBILE 
ORDER BY PRICE ASC
LIMIT 5;

-- TO FIND LIST OF TOP 5 SAMSUNG PHONES WITH PRICE AND ALL FEATURE
SELECT * FROM MOBILE 
WHERE BRANDS = "SAMSUNG"
ORDER BY PRICE DESC
LIMIT 5;

-- MUST HAVE ANDROID PHONE AND LIST THEN TOP 5 HIGH PRICE ANDROID PHONES
SELECT * FROM MOBILE 
WHERE OPERATING_SYSTEM_TYPE = "ANDROID"
ORDER BY PRICE DESC
LIMIT 5; 

-- MUST HAVE ANDROID PHONE AND LIST THEN TOP 5 LOWER PRICE ANDROID PHONES
SELECT * FROM MOBILE
WHERE OPERATING_SYSTEM_TYPE = "ANDROID"
ORDER BY PRICE ASC
LIMIT 5;

-- MUST HAVE IOS PHONE AND LIST THEN TOP 5 HIGH PRICE IOS PHONES
SELECT * FROM MOBILE
WHERE OPERATING_SYSTEM_TYPE = "IOS"
ORDER BY PRICE DESC
LIMIT 5;

-- MUST HAVE IOS PHONE AND LIST THEN TOP 5 LOWER PRICE IOS PHONES
SELECT * FROM MOBILE 
WHERE OPERATING_SYSTEM_TYPE = "IOS"
ORDER BY PRICE ASC
LIMIT 5;

-- WHICH PHONE SUPPORT 5G AND ALSO TOP 5 PHONE WITH 5G SUPPORT;
SELECT * FROM MOBILE
WHERE 5G_AVAILABILITY = "YES"
ORDER BY PRICE DESC
LIMIT 5;

-- TOTAL PRICE OF ALL MOBILE IS TO BE FOUND WITH BRAND NAME 
SELECT BRANDS, SUM(PRICE) FROM MOBILE
GROUP BY BRANDS; 